name: Generate Breakout Game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Breakout Game
        uses: cyprieng/github-breakout@v1.2.3
        with:
          github_username: Thamizh0206

      - name: Push to github-breakout branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: github-breakout
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
