name: Generate Space Shooter Game

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Space Shooter Game
        uses: czl9707/gh-space-shooter@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: Thamizh0206

      - name: Commit and push game GIF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B space-shooter
          mv game.gif ./game.gif
          git add game.gif
          git commit -m "chore: update space shooter game"
          git push origin space-shooter --force
